from cmu_graphics import *
import random
import math

'''
the whole app is written in a way such that it supports any app.width and app.height, I just found 500x500 to be the most enjoyable
loading screen: press any key to skip (or watch the epic intro for the full 30 second duration lol)
home screen: use up and down arrow keys to highlight gamemode, press enter to enter next screen
cool things about home screen: the drivers are random generated each time you open the app, the selection light flashes around the chosen box
driver select screen: use left and right arrows to change driver you choose, arrows once again flash to indicate left or right
driver select screen: press enter to advance to next screen
track select screen: same as driver select screen
free roam game mode is time trial game mode, just without the timing feature, so I will talk about time trial mode below:
time trial: lights out, cannot move before then, cool Mario Kart sound effects for lights out
time trial: top right, shows current lap time and amount of laps completed (if you press up arrow app.numLaps increases, this is for debugging/demo, don't press it!)
time trial: top left, shows the 5 fastest laps completed in order, or if there hasn't been 5 valid laps completed it just shows whatever there is
time trial: press p to pause the game and possibly go back to home screen
time trial: w,a,s,d to move the car. Car rotation works while reversing too (took a while to figure out)
time trial: follow the track to complete a lap, if you cut corners the lap doesn't count and shows "invalid lap" 
time trial: make sure you stay out of the barriers! if you crash into the silver barriers your game is over!
time trial: once you cross the line for the last time, the UI disappears and the car slows down to a stop
game over screen: shows the 5 fastests laps or states that no valid laps have been recorded
game over screen: an option to go back to the home screen and start the game all over again!

grading shortcuts:
on load screen: press any button to skip the intro
in time trial: press up arrow to increase the number of laps (to access game over screens, etc)
'''

class Drivers:
    def __init__(self,name,nationality,team,logoURL,helmetColors,pixelDriverArt,teamColors,teamLogos,flags):
        self.name = name
        self.country = nationality
        self.team = team
        self.logoURL = logoURL
        self.helmetColors = helmetColors
        self.pixelDriverArt = pixelDriverArt
        self.teamColors = teamColors
        self.teamLogos = teamLogos
        self.flags = flags

class Tracks:
    def __init__(self,trackName,trackCountry,trackList,checkPoints,zones,flags,trackOutlines,countryOutlines,trackLogo):
        self.name = trackName
        self.country = trackCountry
        self.polygonList = trackList
        self.checkPoints = checkPoints
        self.zones = zones
        self.flags = flags
        self.trackOutlines = trackOutlines
        self.countryOutlines = countryOutlines
        self.trackLogo = trackLogo

def onAppStart(app):
    #pixel art images below generated by AI Grok
    GR = Drivers('George Russell','UK','Mercedes','termProjectImages/George-Russell-1024x1024+(1).png',rgb(47,163,220),
                 'termProjectImages/3iK3E-removebg-preview.png',rgb(117,241,211),'termProjectImages/Mercedes-AMG_Petronas_F1_Team_logo_(2026).svg',
                 'termProjectImages/Flag_of_the_United_Kingdom.svg.png')
    KA = Drivers('Kimi Antonelli','ITA','Mercedes','termProjectImages/il_570xN.7097366293_1s2w-removebg-preview.png',rgb(19,93,216),
                 'termProjectImages/image__21_-removebg-preview.png',rgb(117,241,211),'termProjectImages/Mercedes-AMG_Petronas_F1_Team_logo_(2026).svg',
                 'termProjectImages/Flag_of_Italy.png')
    CL = Drivers('Charles Leclerc','MCO','Ferrari','termProjectImages/Leclerc-16.svg.png',rgb(241,52,47),
                 'termProjectImages/QVblm-removebg-preview.png',rgb(213,46,55),'termProjectImages/il_1080xN.7198974898_mc15-removebg-preview.png',
                 'termProjectImages/Flag_of_Monaco.png')
    LH = Drivers('Lewis Hamilton','UK','Ferrari','termProjectImages/des-removebg-preview+(2).png',rgb(204,255,0),
                 'termProjectImages/image__1_-removebg-preview.png',rgb(213,46,55),'termProjectImages/il_1080xN.7198974898_mc15-removebg-preview.png',
                 'termProjectImages/Flag_of_the_United_Kingdom.svg.png')
    LN = Drivers('Lando Norris','UK','McLaren','termProjectImages/Lando_Norris_Logo.svg',rgb(210,255,0),
                 'termProjectImages/image__2_-removebg-preview.png',rgb(239,135,51),'termProjectImages/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8+(2)+(1).jpg',
                 'termProjectImages/Flag_of_the_United_Kingdom.svg.png')
    OP = Drivers('Oscar Piastri','AUS','McLaren','termProjectImages/st_small_507x507-pad_600x600_f8f8f8-removebg-preview.png',rgb(232,0,32),
                 'termProjectImages/image__3_-removebg-preview.png',rgb(239,135,51),'termProjectImages/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8+(2)+(1).jpg',
                 'termProjectImages/Flag_of_Australia.svg.png')
    EO = Drivers('Esteban Ocon','FR','Haas','termProjectImages/feb2c65f1fea97322e3d65ef0d597706-removebg-preview.png',rgb(255,60,130),
                 'termProjectImages/image__20_-removebg-preview.png',rgb(223,225,226),'termProjectImages/haas-f1-team-logo-1.png',
                 'termProjectImages/Flag_of_France.png')
    OB = Drivers('Oliver Bearman','UK','Haas','termProjectImages/oliverBearman.png',rgb(255,255,255),
                 'termProjectImages/image__19_-removebg-preview.png',rgb(223,225,226),'termProjectImages/haas-f1-team-logo-1.png',
                 'termProjectImages/Flag_of_the_United_Kingdom.svg.png')
    PG = Drivers('Pierre Gasly','FR','Alpine','termProjectImages/st_small_507x507-pad_600x600_f8f8f8.u1-removebg-preview.png',rgb(100,190,230),
                 'termProjectImages/image__6_-removebg-preview.png',rgb(71,159,226),'termProjectImages/Alpine_F1_Team_Logo.svg.png',
                 'termProjectImages/Flag_of_France.png')
    FC = Drivers('Franco Colapinto','ARG','Alpine','termProjectImages/fc+(1).png',rgb(50,120,200),
                 'termProjectImages/image__7_-removebg-preview.png',rgb(71,159,226),'termProjectImages/Alpine_F1_Team_Logo.svg.png',
                 'termProjectImages/Flag_of_Argentina.png')
    MV = Drivers('Max Verstappen','NLD','Red Bull Racing','termProjectImages/Verstappen-33.svg.png',rgb(15,92,178),
                 'termProjectImages/image__8_-removebg-preview.png',rgb(69,112,192),'termProjectImages/images-removebg-preview.png',
                 'termProjectImages/Flag_of_the_Netherlands.svg.png')
    IH = Drivers('Isack Hadjar','FR','Red Bull Racing','termProjectImages/raf_360x360_075_t_fafafa_ca443f4786.u2-removebg-preview.png',rgb(204,255,0),
                 'termProjectImages/image__9_-removebg-preview.png',rgb(69,112,192),'termProjectImages/images-removebg-preview.png',
                 'termProjectImages/Flag_of_France.png')
    LL = Drivers('Liam Lawson','NZL','Racing Bulls','termProjectImages/Untitled_v1_2026-Jan-10_03-19-08PM-000_CustomizedView41019232807__1___1_-removebg-preview.png',rgb(255,194,13),
                 'termProjectImages/image__10_-removebg-preview.png',rgb(112,145,248),'termProjectImages/racing_bulls-logo_brandlogos.net_bjuef.png',
                 'termProjectImages/Flag_of_New_Zealand.svg.png')
    AL = Drivers('Arvid Lindblad','UK','Racing Bulls','termProjectImages/st_small_507x507-pad_600x600_f8f8f8__1_-removebg-preview.png', rgb(0,51,102),
                 'termProjectImages/image__11_-removebg-preview.png',rgb(112,145,248),'termProjectImages/racing_bulls-logo_brandlogos.net_bjuef.png',
                 'termProjectImages/Flag_of_the_United_Kingdom.svg.png')
    NH = Drivers('Nico Hulkenberg','GER','Audi','termProjectImages/bg_f8f8f8-flat_750x_075_f-pad_750x1000_f8f8f8-removebg-preview.png',rgb(255,255,255),
                 'termProjectImages/image__12_-removebg-preview.png',rgb(235,69,38),'termProjectImages/images+(1)+(1).png',
                 'termProjectImages/Flag_of_germany_800_480.png')
    GB = Drivers('Gabriel Bortoleto','BR','Audi','termProjectImages/Captura-de-pantalla-2025-08-04-154819__1_-removebg-preview.png',rgb(34,34,34),
                 'termProjectImages/image__13_-removebg-preview.png',rgb(235,69,38),'termProjectImages/images+(1)+(1).png',
                 'termProjectImages/Brazil_flag_300.png')
    CS = Drivers('Carlos Sainz','ESP','Williams','termProjectImages/flat_750x_075_f-pad_750x1000_f8f8f8__1_-removebg-preview.png',rgb(220,30,35),
                 'termProjectImages/image__14_-removebg-preview.png',rgb(50,103,212),'termProjectImages/Logo_Williams_F1.png',
                 'termProjectImages/Spain_flag_300.png')
    AA = Drivers('Alex Albon','THA','Williams','termProjectImages/GFbL_8IXgAAYAWs+(1).jpg',rgb(250,250,250),
                 'termProjectImages/image__15_-removebg-preview.png',rgb(50,103,212),'termProjectImages/Logo_Williams_F1.png',
                 'termProjectImages/Flag_of_Thailand.svg.png')
    SP = Drivers('Sergio Perez','MEX','Cadillac','termProjectImages/Captura-de-pantalla-2024-04-29-153735-removebg-preview.png', rgb(255,255,51),
                 'termProjectImages/image__16_-removebg-preview.png',rgb(170,170,173),'termProjectImages/Cadillac_Formula_1_Team_logo.png',
                 'termProjectImages/Flag_of_Mexico.png')
    VB = Drivers('Valterri Bottas','FIN','Cadillac','termProjectImages/bg_f8f8f8-flat_750x_075_f-pad_750x1000_f8f8f8.u6__1_-removebg-preview.png',rgb(180,72,255),
                 'termProjectImages/image__17_-removebg-preview.png',rgb(170,170,173),'termProjectImages/Cadillac_Formula_1_Team_logo.png',
                 'termProjectImages/Finland_Large_Flag.png')
    FA = Drivers('Fernando Alonso','ESP','Aston Martin','termProjectImages/i_m_pid_487,c_76_80_1108x887,bc_000000,ar_4x5,o_landscape,pm_4,s_630,q_90+(1).jpg', rgb(255,235,59),
                 'termProjectImages/image__18_-removebg-preview.png',rgb(75,151,116),'termProjectImages/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8+(1)+(1).jpg',
                 'termProjectImages/Spain_flag_300.png')
    LS = Drivers('Lance Stroll','CAN','Aston Martin','termProjectImages/i_m_pid_2834_c_s_auto_bg_bc_000000_s_630_q_90-removebg-preview.png',rgb(3,122,104),
                 'termProjectImages/GA5Oi-removebg-preview.png',rgb(75,151,116),'termProjectImages/bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8+(1)+(1).jpg',
                 'termProjectImages/Flag_of_Canada_(Pantone).png')
    app.allDrivers = [GR,KA,CL,LH,LN,OP,EO,OB,
                      PG,FC,MV,IH,LL,AL,NH,GB,
                      CS,AA,SP,VB,FA,LS]
    monzaList = [([0,0,0,10000,10000,10000,10000,0],'green'),
                  #outside barriers, generated by AI Gemini
                 ([2275,9200,9425,9200,9425,9225,2275,9225],'silver'),
                 ([2275,6575,2300,6575,2300,9225,2275,9225],'silver'),
                 ([1975,6575,2300,6575,2300,6550,1975,6550],'silver'),
                 ([1975,4475,2000,4475,2000,6550,1975,6550],'silver'),
                 ([1975,4475,3625,4475,3625,4500,1975,4500],'silver'),
                 ([3600,4475,3625,4475,3625,6700,3600,6700],'silver'),
                 ([3600,6675,9425,6675,9425,6700,3600,6700],'silver'),
                 ([9400,6675,9425,6675,9425,9225,9400,9225],'silver'),
                  #inside barrier, generated by AI Gemini
                 ([2875,8600,4275,8600,4275,8625,2875,8625],'silver'),
                 ([5025,8600,8825,8600,8825,8625,5025,8625],'silver'),
                 ([4250,8350,4275,8350,4275,8625,4250,8625],'silver'),
                 ([4250,8350,5050,8350,5050,8375,4250,8375],'silver'),
                 ([5025,8350,5050,8350,5050,8625,5025,8625],'silver'),
                 ([8800,7275,8825,7275,8825,8625,8800,8625],'silver'),
                 ([3000,7275,8825,7275,8825,7300,3000,7300],'silver'),
                 ([3000,5075,3025,5075,3025,7300,3000,7300],'silver'),
                 ([2575,5075,3025,5075,3025,5100,2575,5100],'silver'),
                 ([2575,5075,2600,5075,2600,6125,2575,6125],'silver'),
                 ([2575,6100,2900,6100,2900,6125,2575,6125],'silver'),
                 ([2875,6100,2900,6100,2900,8625,2875,8625],'silver'),
                  #track
                 ([4900,8800,9001,8800,9001,9000,4900,9000],'grey'),
                 ([4799,8400,5000,8400,5000,9000,4799,9000],'grey'),
                 ([4600,8550,4800,8400,4800,8750,4500,9000,3900,9000,3900,8800,4100,8800],'grey'),
                 ([2899,8800,3901,8800,3901,9000,2899,9000],'grey'),
                 ([2500,8600,2700,8600,2900,8800,2900,9000,2650,8850],'grey'),
                 ([2500,6499,2700,6499,2700,8601,2500,8601],'grey'),
                 ([2200,6300,2700,6300,2700,6500,2200,6500],'grey'),
                 ([2200,4899,2400,4899,2400,6301,2200,6301],'grey'),
                 ([2200,4700,3400,4700,3400,4900,2200,4900],'grey'),
                 ([3200,4899,3400,4899,3400,6401,3200,6401],'grey'),
                 ([3200,6400,3400,6400,3700,6900,3700,7100,3375,6925],'grey'),
                 ([3699,6900,9001,6900,9001,7100,3699,7100],'grey'),
                 ([9000,6900,9200,6900,9200,9000,9000,9000],'grey'),
                 #start line
                 ([5400,8800,5500,8800,5500,9000,5400,9000],'blue')]
    indianapolisList = [([0,0,0,10000,10000,10000,10000,0],'green'),
                        #outside barriers
                        ([2275,2275,7725,2275,7725,2300,2275,2300],'silver'),
                        ([7700,2275,7725,2275,7725,7725,7700,7725],'silver'),
                        ([7725,7700,7700,7725,2275,7725,2275,7700],'silver'),
                        ([2275,2275,2300,2275,2300,7725,2275,7725],'silver'),
                        #inside barriers
                        ([2875,2875,7125,2875,7125,2900,2875,2900],'silver'),
                        ([7100,2875,7125,2875,7125,7125,7100,7125],'silver'),
                        ([7125,7100,7100,7125,2875,7125,2875,7100],'silver'),
                        ([2875,2875,2900,2875,2900,7125,2875,7125],'silver'),
                        #track
                        ([2500,2500,2700,2500,2700,7500,2500,7500],'grey'),
                        ([2500,2500,7500,2500,7500,2700,2500,2700],'grey'),
                        ([7300,2500,7500,2500,7500,7500,7300,7500],'grey'),
                        ([2500,7300,7500,7300,7500,7500,2500,7500],'grey'),
                        #start line
                        ([2500,5000,2700,5000,2700,5100,2500,5100],'blue')]
    monzaList = addLightGreenStrips(app,monzaList)
    indianapolistList = addLightGreenStrips(app,indianapolisList)
    indianapolisCheckPoints = [(2500,2700,5000,5100),(2500,2700,2500,2700),
                               (7200,7500,2500,2700),(7200,7500,7200,7500),(2500,2700,7200,7500)]
    indianapolisZones = [(2325,7675,2325,2850),(7150,7675,2325,7676),(2325,7675,7150,7675),(2325,2850,2325,7675)]
    monzaCheckPoints = [(5400,5500,8800,9000),(4800,5000,8800,9000),(4800,5000,8400,8745),(3900,4100,8800,9000),(2725,2875,8745,9000),
                        (2500,2700,8440,8585),(2500,2700,6300,6500),(2200,2400,6300,6500),(2200,2400,4700,4900),(3200,3400,4700,4900),
                        (3200,3410,6400,6600),(3700,3900,6900,7100),(9000,9200,6900,7100),(9000,9200,8800,9000)]
    monzaZones = [(2325,9375,8650,9175),(4295,5000,8410,9175),(2325,2850,6425,9175),(2025,2850,6150,6530),(2020,2550,4525,6525),
                  (2025,3575,4525,5055),(3050,3575,4525,7250),(3050,9375,6725,7250),(8850,9375,6725,9175)]
    monza = Tracks('Monza','ITA',monzaList,monzaCheckPoints,monzaZones,'termProjectImages/Flag_of_Italy.png',
                   'termProjectImages/Monza-removebg-preview.png','termProjectImages/69c3f73ce4e20__700-removebg-preview__1_-removebg-preview.png',
                   'termProjectImages/Logo_Monza.png')
    indianapolis = Tracks('Indianapolis','USA',indianapolisList,indianapolisCheckPoints,indianapolisZones,'termProjectImages/Flag_of_the_United_States.png',
                   'termProjectImages/Combo.image-removebg-preview.png','termProjectImages/2161027-200.png',
                   'termProjectImages/kisspng-indianapolis-motor-speedway-2016-indianapolis-500-marshall-5acc60c5019d29.7949538215233435570066-removebg-preview.png')
    app.allTracks = [monza,indianapolis]
    app.smoke = 'termProjectImages/fireImage-removebg-preview.png'
    #sound from: https://www.youtube.com/watch?v=_TcXaAcbQ5Q
    app.introSound = Sound('termProjectImages/Epic+Cinematic+Tension+Intro+(Royalty+Free+Music).mp3')
    #audio from https://www.youtube.com/watch?v=Sks_fMr2Yss
    app.homeScreenSound = Sound('termProjectImages/New+2026+F1+Opening+Titles.mp3')
    #audio from RibhavAgrawal
    app.SelectionSound = Sound('termProjectImages/ribhavagrawal-point-smooth-beep-230573+(mp3cut.net).mp3')
    #audio from marioKart wii
    app.lightsSound = Sound('termProjectImages/Mario+Kart+Race+Start+-+Sound+Effect+(HD)+(mp3cut.net)+(1).mp3')
    app.lightsOutSound = Sound('termProjectImages/Mario+Kart+Race+Start+-+Sound+Effect+(HD)+(mp3cut.net).mp3')
    resetApp(app)

def addLightGreenStrips(app,trackList):
    startX,startY = 2500, -1300
    width, height = 100000,100
    numDivs = 100
    for i in range(numDivs//2):
        polygon = [startX,startY,startX + width,startY,startX + width,startY + height,startX,startY+height]
        newPolygon = []
        for i in range(0,len(polygon),2):
            x, y = polygon[i],polygon[i + 1]
            radians = math.radians(25)
            cosTheta = math.cos(radians)
            sinTheta = math.sin(radians)
            pivotX = app.width / 2
            pivotY = app.height / 2
            tempX = x - pivotX
            tempY = y - pivotY
            rotatedX = tempX * cosTheta - tempY * sinTheta
            rotatedY = tempX * sinTheta + tempY * cosTheta
            finalX = rotatedX + pivotX
            finalY = rotatedY + pivotY
            newPolygon.append(finalX)
            newPolygon.append(finalY)
        newTuple = (newPolygon,'lightGreen')
        trackList.insert(1,newTuple)
        startY += height * 2
    return trackList
    
def resetApp(app):
    app.loadScreenCounter = 0
    app.selectionCounter = 0
    app.selectedMode = 'Time Trial'
    app.selectionCounterInc = True
    app.driverSelect = False
    app.driverSelectChoices = ['Left','Buffer','Right']
    app.choicesIndex = 1
    app.driverIndex = 0
    app.selectedDriver = None
    app.trackIndex = 0
    app.timeTrialTimer = 0
    app.driverIntroCounter = -(100/400) * app.width
    app.carState = 'straight'
    app.carX = 0
    app.carY = 0
    app.angle = 0
    app.carSpeed = 0
    app.lapTimes = [None,None,None,None,None]
    app.selectedTrack = app.allTracks[0]
    app.checkPointsCleared = set()
    app.invalidLap = False
    app.driverOne,app.driverTwo = getRandomDrivers(app)
    app.laps = 1
    app.paused = False
    app.pauseSelection = 'Resume'
    app.gameOver = False
    app.gameOverCounter = 0
    app.crashed = False

def getRandomDrivers(app):
    randomIndexOne, randomIndexTwo = random.sample(range(len(app.allDrivers)),2)
    driverOne = app.allDrivers[randomIndexOne]
    driverTwo = app.allDrivers[randomIndexTwo]
    return driverOne,driverTwo    

##################################
# load screen
##################################

def load_redrawAll(app):
    if app.loadScreenCounter <= 1000:
        textOpacity = 0.1*app.loadScreenCounter
        drawLabelAndLogo(app,textOpacity)
    elif 1000 <= app.loadScreenCounter < 2000:
        textOpacity = 100 - 0.1*(app.loadScreenCounter % 1000)
        drawLabelAndLogo(app,textOpacity)

def drawLabelAndLogo(app,textOpacity):
    drawRect(0,0,app.width,app.height)
    drawLabel('Presented by Brenner Entertainment',app.width//2,(1/4) * app.height,size=16,bold=True,fill='white',opacity=textOpacity)
    squareLength = (125/400) * app.width
    drawRect(app.width//2,(3/4) * app.height,squareLength,squareLength,rotateAngle=45,fill='white',align='center',opacity=textOpacity)
    drawLabel('B',app.width//2,(3/4) * app.height,size=30,fill='black',bold=True,opacity=textOpacity)

def load_onStep(app):
    app.loadScreenCounter += 2.45
    if app.loadScreenCounter > 2000:
        setActiveScreen('home')
    app.introSound.play(restart=False,loop=False)

def load_onKeyPress(app,keys):
    setActiveScreen('home')

###################################
# home screen
###################################

def home_redrawAll(app):
    drawRect(0,0,app.width,app.height,fill='fireBrick')
    drawLabel('Formula-112',app.width//2,(1/4)*app.height,size=30,bold=True,fill='darkOrange')
    optionWidth, optionHeight = (150/400) * app.width, (50/400) * app.height
    drawRect(app.width//2,(5/8) * app.height,optionWidth,optionHeight,align='center',border='black',borderWidth=2,fill='gold')
    drawRect(app.width//2,(13/16) * app.height,optionWidth,optionHeight,align='center',border='black',borderWidth=2,fill='gold')
    drawLabel('Time Trial',app.width//2,(5/8) * app.height)
    drawLabel('Free Roam',app.width//2,(13/16) * app.height)
    if app.selectedMode == 'Time Trial':
        drawRect(app.width//2,(5/8) * app.height,optionWidth,optionHeight,fill=None,align='center',border='yellow',opacity=getFlashingOpacity(app))
    else: #free roam
        drawRect(app.width//2,(13/16) * app.height,optionWidth,optionHeight,fill=None,align='center',border='yellow',opacity=getFlashingOpacity(app))
    drawLabel('Brenner Entertainment LLC, 2026',app.width - 2,app.height - 2,align='right-bottom',size=7)
    drawDriversEnteringFromSides(app)

def drawDriversEnteringFromSides(app):
    driverOneURL = app.driverOne.pixelDriverArt
    driverTwoURL = app.driverTwo.pixelDriverArt
    driverOneCx = (1/7) * app.width + app.driverIntroCounter
    driverTwoCx = (6/7) * app.width - app.driverIntroCounter
    driverCy = app.height//2
    driverWidth = (125/400) * app.width
    driverHeight = (190/400) * app.height
    drawImage(driverOneURL,driverOneCx,driverCy,align='center',width=driverWidth,height=driverHeight)
    drawImage(driverTwoURL,driverTwoCx,driverCy,align='center',width=driverWidth,height=driverHeight)

def getFlashingOpacity(app):
    flashingOpacity = 10 * app.selectionCounter
    if flashingOpacity >= 100:
        flashingOpacity = 100
    elif flashingOpacity <= 0:
        flashingOpacity = 0
    return flashingOpacity

def home_onKeyPress(app,key):
    if key == 'up':
        app.selectedMode = 'Time Trial'
    elif key == 'down':
        app.selectedMode = 'Free Roam'
    elif key == 'enter':
        setActiveScreen('driverSelect')
    
def home_onStep(app):
    app.introSound.pause()
    app.homeScreenSound.play(loop=True)
    selectionCounterLogic(app)
    if app.driverIntroCounter < 0:
        app.driverIntroCounter += 2
    
def selectionCounterLogic(app):
    if app.selectionCounterInc:
        app.selectionCounter += 0.75
    else:
        app.selectionCounter -= 0.75
    if app.selectionCounter >= 10:
        app.selectionCounterInc = False
    if app.selectionCounter <= 0:
        app.selectionCounterInc = True

###############################
# driver select
###############################

def driverSelect_redrawAll(app):
    curDriver = app.allDrivers[app.driverIndex]
    drawBackground(app,curDriver)
    drawSelectionArrows(app)
    drawDriverName(app,curDriver)
    drawCurDriverLogo(app,curDriver)
    drawDriverTeam(app,curDriver)
    drawFlag(app,curDriver) 
    draw8BitDriver(app,curDriver)
    drawTeamLogo(app,curDriver)

def drawBackground(app,curDriver):
    backgroundColor = curDriver.teamColors
    drawRect(0,0,app.width,app.height,fill=backgroundColor)

def drawSelectionArrows(app):
    drawPolygon(app.width//10,app.height//2,app.width//5,(3/8)*app.height,app.width//5,(5/8)*app.height,fill='gold')
    drawPolygon(app.width - app.width//10,app.height//2,app.width - app.width//5,(3/8)*app.height,app.width - app.width//5,(5/8)*app.height,fill='gold')
    flashingOpacity = getFlashingOpacity(app)
    if app.choicesIndex == 0:
        drawPolygon(app.width//10,app.height//2,app.width//5,(3/8)*app.height,app.width//5,(5/8)*app.height,fill=None,border='yellow',borderWidth=5,opacity=flashingOpacity)
    elif app.choicesIndex == 2:
        drawPolygon(app.width - app.width//10,app.height//2,app.width - app.width//5,(3/8)*app.height,app.width - app.width//5,(5/8)*app.height,fill=None,border='yellow',borderWidth=5,opacity=flashingOpacity)

def drawDriverName(app,curDriver):
    drawLabel(curDriver.name,app.width//2,(13/16) * app.height,size=18,bold=True)

def drawCurDriverLogo(app,driver):
    logoCx, logoCy = (5/32) * app.width,(5/32) * app.height
    logoURL = driver.logoURL
    logoWidth = (100/400) * app.width
    logoHeight = (100/400) * app.height
    drawImage(logoURL,logoCx,logoCy,align='center',width=logoWidth,height=logoHeight)

def drawDriverTeam(app,curDriver):
    drawLabel(curDriver.team,(5/32) * app.width,(56/64) * app.height,size=18,bold=True)

def drawFlag(app,driver):
    flagCx = app.width - (7/32) * app.width
    flagCy = (5/32) * app.height
    flagURL = driver.flags
    flagWidth = (100/400) * app.width
    flagHeight = (60/400) * app.height
    adjustment = (3/400) * app.width
    drawRect(flagCx,flagCy,flagWidth+adjustment,flagHeight+adjustment,fill=None,border='black',borderWidth=5,align='center')
    drawImage(flagURL,flagCx,flagCy,align='center',width=flagWidth,height=flagHeight)

def draw8BitDriver(app,driver):
    driverCx = app.width // 2
    driverCy = app.height // 2
    driverURL = driver.pixelDriverArt
    driverWidth = (125/400) * app.width
    driverHeight = (190/400) * app.height
    drawImage(driverURL,driverCx,driverCy,width=driverWidth,height=driverHeight,align='center')

def drawTeamLogo(app,driver):
    logoURL = driver.teamLogos
    logoCx = app.width - (7/32) * app.width
    logoCy = app.height - (5/32) * app.height
    logoWidth = (100/400) * app.width
    logoHeight = (100/400) * app.height
    adjustment = (3/400) * app.width
    if driver.team == 'Aston Martin':
        drawRect(logoCx,logoCy,logoWidth + adjustment,logoHeight + adjustment,align='center',fill=None,border = 'black', borderWidth=adjustment)
    if driver.team == 'Audi':
        drawRect(logoCx,logoCy,logoWidth + adjustment,logoHeight + adjustment,align='center',fill=None,border = 'orange', borderWidth=adjustment)
    drawImage(logoURL,logoCx,logoCy,align='center',width=logoWidth,height=logoHeight)

def driverSelect_onKeyPress(app,key):
    if key == 'left':
        if app.choicesIndex >= 1:
            app.choicesIndex -= 1
        else:
            if app.driverIndex == 0:
                app.driverIndex = len(app.allDrivers) - 1
            else:
                app.driverIndex -= 1
    elif key == 'right':
        if app.choicesIndex < 2:
            app.choicesIndex += 1
        else:
            app.driverIndex += 1
            app.driverIndex %= len(app.allDrivers)
    elif key == 'enter':
        app.selectedDriver = app.allDrivers[app.driverIndex]
        app.choicesIndex = 1
        setActiveScreen('trackSelect')

def driverSelect_onStep(app):
    selectionCounterLogic(app)

##################################
# track select
##################################

def trackSelect_redrawAll(app):
    drawTrackSelectBackground(app)
    drawTrackFlag(app)
    drawTrackOutline(app)
    drawCountryOutline(app)
    drawTrackLogo(app)
    drawTrackCountryStr(app)
    drawSelectionArrows(app)

def drawTrackSelectBackground(app):
    if app.selectedTrack.name == 'Monza':
        color = 'crimson'
    else:
        color = 'dodgerBlue'
    drawRect(0,0,app.width,app.height,fill=color)

def drawTrackOutline(app):
    logoCx, logoCy = (5/32) * app.width,(5/32) * app.height
    logoURL = app.selectedTrack.trackOutlines
    logoWidth = (100/400) * app.width
    logoHeight = (100/400) * app.height
    drawImage(logoURL,logoCx,logoCy,align='center',width=logoWidth,height=logoHeight)

def drawCountryOutline(app):
    logoURL = app.selectedTrack.countryOutlines
    logoCx = app.width - (7/32) * app.width
    logoCy = app.height - (5/32) * app.height
    logoWidth = (100/400) * app.width
    logoHeight = (100/400) * app.height
    adjustment = (3/400) * app.width
    drawImage(logoURL,logoCx,logoCy,align='center',width=logoWidth,height=logoHeight)
    
def drawTrackFlag(app):
    flagCx = app.width - (7/32) * app.width
    flagCy = (5/32) * app.height
    flagURL = app.selectedTrack.flags
    flagWidth = (100/400) * app.width
    flagHeight = (60/400) * app.height
    adjustment = (3/400) * app.width
    drawRect(flagCx,flagCy,flagWidth+adjustment,flagHeight+adjustment,fill=None,border='black',borderWidth=5,align='center')
    drawImage(flagURL,flagCx,flagCy,align='center',width=flagWidth,height=flagHeight)

def drawTrackLogo(app):
    imageURL = app.selectedTrack.trackLogo
    if app.selectedTrack.name == 'Monza':
        imageWidth = 150
        imageHeight = 150
        drawImage(imageURL,app.width/2,app.height/2,align='center',width=imageWidth,height=imageHeight)
    else:
        imageWidth = 250
        imageHeight = 125
        drawImage(imageURL,app.width/2,app.height/2,align='center',width=imageWidth,height=imageHeight)
    
def drawTrackCountryStr(app):
    if app.selectedTrack.country == 'ITA':
        string = 'Italy'
    else:
        string = 'USA'
    drawLabel(string,(5/32) * app.width,(56/64) * app.height,size=20,bold=True)

def trackSelect_onKeyPress(app,key):
    if key == 'left':
        if app.choicesIndex >= 1:
            app.choicesIndex -= 1
        else:
            if app.trackIndex == 0:
                app.trackIndex = len(app.allTracks) - 1
            else:
                app.trackIndex -= 1
            app.selectedTrack = app.allTracks[app.trackIndex]
    elif key == 'right':
        if app.choicesIndex < 2:
            app.choicesIndex += 1
        else:
            app.trackIndex += 1
            app.trackIndex %= len(app.allTracks)
            app.selectedTrack = app.allTracks[app.trackIndex]
    elif key == 'enter':
        app.trackSelect = False
        app.selectedTrack = app.allTracks[app.trackIndex]
        initializeTrackValues(app)
        if app.selectedMode == 'Free Roam':
            app.timeTrialTimer = 1
            setActiveScreen('freeRoam')
        else:
            app.timeTrialTimer = -210
            setActiveScreen('timeTrial')
    
def initializeTrackValues(app):
    if app.selectedTrack.name == 'Indianapolis':
        app.carX = 2600
        app.carY = 5100
        app.angle = 90
    elif app.selectedTrack.name == 'Monza':
        app.carX = 5500
        app.carY = 8900
        app.angle = 180

def trackSelect_onStep(app):
    selectionCounterLogic(app)

##########################
# time trial
##########################

def timeTrial_redrawAll(app):
    drawCurrentTrack(app)
    drawCar(app)
    if app.crashed:
        drawCrashFire(app)
    if not app.gameOver:
        if app.timeTrialTimer < 0:
            drawLightsOut(app)
        else:
            drawTimer(app)
            drawLaptimes(app)
            drawLapCounter(app)
            if app.invalidLap:
                drawInvalidLapLabel(app)
    if app.paused:
        drawGamePauseScreen(app)

def drawCurrentTrack(app):
    for coordsList, color in app.selectedTrack.polygonList:
        adjustedList = adjustList(app,coordsList)
        drawPolygon(*adjustedList,fill=color)

def adjustList(app,coordsList):
    res = []
    for i in range(0,len(coordsList),2):
        x, y = coordsList[i], coordsList[i + 1]
        x = x - app.carX + app.width/2
        y = y - app.carY + app.height/2
        x,y = rotateViaPolar(app,x,y,app.angle-90)
        res.append(x)
        res.append(y)
    return res

#this function was written with help from AI gemini
def rotateViaPolar(app,x,y,angle):
    radians = math.radians(angle)
    cosTheta = math.cos(radians)
    sinTheta = math.sin(radians)
    pivotX = app.width / 2
    pivotY = app.height / 2
    tempX = x - pivotX
    tempY = y - pivotY
    rotatedX = tempX * cosTheta - tempY * sinTheta
    rotatedY = tempX * sinTheta + tempY * cosTheta
    finalX = rotatedX + pivotX
    finalY = rotatedY + pivotY
    return finalX, finalY

def drawCar(app):
    curDriver = app.allDrivers[app.driverIndex]
    carCol = curDriver.teamColors
    driverCol = curDriver.helmetColors
    drawMainBody(app,carCol,driverCol)
    drawFrontWheels(app)

def drawMainBody(app,carCol,driverCol):
    drawFWG(app,carCol)
    drawBody(app,carCol)
    drawRWG(app,carCol)
    drawSID(app,carCol)
    drawDriver(app,driverCol)
    drawSuspencion(app)
    drawRearWheels(app)

def drawFWG(app,carCol):
    fwgWidth = (46/400) * app.width
    fwgHeight = (10/400) * app.height
    adjustment = (30/400) * app.height
    drawRect(app.width//2,app.height//2 - adjustment,fwgWidth,fwgHeight,align='center',fill=carCol)
    
def drawBody(app,carCol):
    bodyWidth = (20/400) * app.width
    bodyHeight = (60/400) * app.height
    drawRect(app.width//2,app.height//2,bodyWidth,bodyHeight,align='center',fill=carCol)

def drawRWG(app,carCol):
    rwgWidth = (46/400) * app.width
    rwgHeight = (12/400) * app.height
    adjustment = (30/400) * app.height
    drawRect(app.width//2,app.height//2 + adjustment,rwgWidth,rwgHeight,align='center',fill=carCol)

def drawSID(app,carCol):
    sid1X1, sid1Y1 = (191/400) * app.width, (190/400) * app.height
    sid1X2, sid1Y2 = (175/400) * app.width, (190/400) * app.height
    sid1X3, sid1Y3 = (191/400) * app.width, (215/400) * app.height
    drawPolygon(sid1X1,sid1Y1,sid1X2,sid1Y2,sid1X3,sid1Y3,fill=carCol)
    sid2X1, sid2Y1 = (209/400) * app.width, (190/400) * app.height
    sid2X2, sid2Y2 = (226/400) * app.width, (190/400) * app.height
    sid2X3, sid2Y3 = (209/400) * app.width, (215/400) * app.height
    drawPolygon(sid2X1,sid2Y1,sid2X2,sid2Y2,sid2X3,sid2Y3,fill=carCol)

def drawDriver(app,driverCol):
    adjustment = (5/400) * app.height
    drawCircle(app.width//2,app.height//2 + adjustment,(5/400)*app.width,fill=driverCol)

def drawSuspencion(app):
    leftX1 = (190/400) * app.width
    leftX2 = (180/400) * app.width
    rightX1 = (210/400) * app.width
    rightX2 = (220/400) * app.width
    frontY = (182/400) * app.height
    backY = (217/400) * app.height
    drawLine(leftX1,frontY,leftX2,frontY)
    drawLine(rightX1,frontY,rightX2,frontY)
    drawLine(leftX1,backY,leftX2,backY)
    drawLine(rightX1,backY,rightX2,backY)
    
def drawRearWheels(app):
    rearWheel1X = (181/400) * app.width
    rearWheel2X = (219/400) * app.width
    rearWheelY = (217/400) * app.height
    wheelWidth, wheelHeight = (6/400) * app.width, (11/400) * app.height
    drawRect(rearWheel1X,rearWheelY,wheelWidth,wheelHeight,align='center')
    drawRect(rearWheel2X,rearWheelY,wheelWidth,wheelHeight,align='center')

def drawFrontWheels(app):
    if app.carState == 'straight':
        angle = 0
    elif app.carState == 'left':
        angle = 315
    else: #app.carState == right
        angle = 45
    wheelWidth, wheelHeight = (6/400) * app.width, (11/400) * app.height
    frontWheelX1 = (181/400) * app.width
    frontWheelX2 = (219/400) * app.width
    frontWheelY = (182/400) * app.height
    drawRect(frontWheelX1,frontWheelY,wheelWidth,wheelHeight,rotateAngle=angle,align='center')
    drawRect(frontWheelX2,frontWheelY,wheelWidth,wheelHeight,rotateAngle=angle,align='center')

def drawLightsOut(app):
    numLights = 5 - (abs(app.timeTrialTimer) // 30)
    for i in range(numLights):
        lightCx,lightCy = getLocationOfLights(app,i)
        drawCircle(lightCx,lightCy,20,fill='red',border='black')
  
def getLocationOfLights(app,lightNum):
    cy = app.height // 5
    baseCx = app.width // 4
    numLights = 5
    dx = (app.width // 2) // (numLights - 1)
    cx = baseCx + dx * lightNum
    return cx, cy

def drawTimer(app):
    absoluteSeconds = app.timeTrialTimer // 30
    decimalSeconds = (app.timeTrialTimer % 30) / 30
    minute = absoluteSeconds // 60
    seconds = absoluteSeconds % 60
    adjustment = (2/400) * app.width
    #f string below generated by AI Gemini
    drawLabel(f'{minute}:{seconds:02}:{decimalSeconds*100:02.0f}',app.width - adjustment,adjustment,align='right-top',size=20,bold=True)

def drawLaptimes(app):
    adjustment = (25/400) * app.height
    numLaps = 5
    for i in range(numLaps):
        x, y = (10/400) * app.width, (10/400) * app.height + adjustment * i
        curLaptime = app.lapTimes[i]
        if curLaptime != None:
            drawLabel(f'{i + 1} : {getTime(curLaptime)}',x,y,size=20,bold=True,align='left-top')

def getTime(time):
    absoluteSeconds = time // 30
    decimalSeconds = (time % 30) / 30
    minute = absoluteSeconds // 60
    seconds = absoluteSeconds % 60
    return f'{minute}:{seconds:02}:{decimalSeconds*100:02.0f}'

def drawLapCounter(app):
    adjustment = (2/400) * app.width
    increaseInY = (20/400) * app.height
    drawLabel(f'Lap {app.laps}/10',app.width - adjustment,adjustment + increaseInY,size=20,bold=True,align='right-top')

def drawInvalidLapLabel(app):
    drawLabel('Invalid Lap!',app.width/2,(1/8)*app.height,size=20,bold=True,fill='purple')

def drawGamePauseScreen(app):
    screenSize = (5/8) * app.width
    drawRect(app.width/2,app.height/2,screenSize,screenSize,align='center',fill='purple',border='black',borderWidth=2)
    optionWidth, optionHeight = (150/400) * app.width, (50/400) * app.height
    drawRect(app.width//2,(3/8) * app.height,optionWidth,optionHeight,align='center',border='black',borderWidth=2,fill='gold')
    drawRect(app.width//2,(5/8) * app.height,optionWidth,optionHeight,align='center',border='black',borderWidth=2,fill='gold')
    drawLabel('Resume',app.width//2,(3/8) * app.height)
    drawLabel('Exit to main menu',app.width//2,(5/8) * app.height)
    if app.pauseSelection == 'Resume':
        drawRect(app.width//2,(3/8) * app.height,optionWidth,optionHeight,fill=None,align='center',border='yellow',opacity=getFlashingOpacity(app))
    else: #exit
        drawRect(app.width//2,(5/8) * app.height,optionWidth,optionHeight,fill=None,align='center',border='yellow',opacity=getFlashingOpacity(app))

def drawCrashFire(app):
    x, y = app.width/2, app.height/2
    x, y = rotateViaPolar(app,x,y,app.angle-90)
    drawImage(app.smoke,x,y,align='center',width=100,height=100)
    
def timeTrial_onKeyPress(app,key):
    if key == 'p':
        app.paused = True
    if key == 'up':
        app.laps += 1
    if app.paused:
        if key == 'up':
            app.pauseSelection = 'Resume'
        elif key == 'down':
            app.pauseSelection = 'Exit'
        elif key == 'enter':
            if app.pauseSelection == 'Resume':
                app.paused = False
            else:
                resetApp(app)
                setActiveScreen('home')
        
def timeTrial_onKeyHold(app,keys):
    if app.timeTrialTimer > 0 and not app.gameOver:
        controlCarStatesOnHold(app,keys)

def controlCarStatesOnHold(app,keys):
    if not app.paused:
        if 'a' in keys and 'd' not in keys:
            app.carState = 'left'
        elif 'd' in keys and 'a' not in keys:
            app.carState = 'right'
        else:
            app.carState = 'straight'
        if 'w' in keys and 's' not in keys and app.carSpeed < 20:
            app.carSpeed += 0.25
        elif 's' in keys and 'w' not in keys and app.carSpeed > -20:
            app.carSpeed -= 0.25
        if app.carSpeed > 0:
            if 'd' in keys and 'a' not in keys:
                app.angle -= 5
            elif 'a' in keys and 'd' not in keys:
                app.angle += 5
        elif app.carSpeed < 0:
            if 'd' in keys and 'a' not in keys:
                app.angle += 5
            elif 'a' in keys and 'd' not in keys:
                app.angle -= 5

def timeTrial_onKeyRelease(app,keys):
    controlCarStatesOnRelease(app,keys)

def controlCarStatesOnRelease(app,keys):
    if 'w' not in keys:
        app.carState = 'straight'

def timeTrial_onStep(app):
    if app.timeTrialTimer < 0 and app.timeTrialTimer % 30 == 0 and app.timeTrialTimer > -160:
        app.lightsSound.play()
    if app.timeTrialTimer == 0:
        app.lightsOutSound.play()
    app.homeScreenSound.pause()
    if not app.paused and not app.crashed:
        controlCarStateOnStep(app)
        app.timeTrialTimer += 1
        curTrackCheckpoints = app.selectedTrack.checkPoints
        for i in range(len(curTrackCheckpoints)):
            x1,x2,y1,y2 = curTrackCheckpoints[i]
            if i == 0 and x1 <= app.carX <= x2 and y1 <= app.carY <= y2 and app.checkPointsCleared == set(curTrackCheckpoints):
                changeLaptimes(app)
                app.timeTrialTimer = 1
                app.checkPointsCleared = set([curTrackCheckpoints[i]])
                app.laps += 1
            elif i == 0 and x1 <= app.carX <= x2 and y1 <= app.carY <= y2 and app.checkPointsCleared != set(curTrackCheckpoints) and (len(app.checkPointsCleared) > 1 or app.timeTrialTimer > 600):
                app.timeTrialTimer = 1
                app.invalidLap = True
                app.checkPointsCleared = set([curTrackCheckpoints[0]])
                app.laps += 1
            else:
                if x1 <= app.carX <= x2 and y1 <= app.carY <= y2:
                    app.checkPointsCleared.add(curTrackCheckpoints[i])
            if app.laps >= 11:
                app.gameOver = True
        if app.timeTrialTimer > 100:
            app.invalidLap = False
        if app.gameOver:
            app.gameOverCounter += 1
    selectionCounterLogic(app)
    crashLogic(app)

def controlCarStateOnStep(app):
    if app.gameOver:
        if app.carSpeed > 0:
            app.carSpeed -= 0.25
        elif app.carSpeed < 0:
            app.carSpeed += 0.25
    else:
        if app.carSpeed > 0:
            app.carSpeed -= 0.125
        elif app.carSpeed < 0:
            app.carSpeed += 0.125
    app.carX += math.cos(math.radians(app.angle)) * app.carSpeed
    app.carY -= math.sin(math.radians(app.angle)) * app.carSpeed

def changeLaptimes(app):
    curLap = app.timeTrialTimer
    for i in range(len(app.lapTimes)):
        if app.lapTimes[i] == None:
            app.lapTimes[i] = curLap
            return
        if curLap < app.lapTimes[i]:
            app.lapTimes.insert(i,curLap)
            app.lapTimes.pop()
            return

def crashLogic(app):
    if app.crashed:
        app.gameOverCounter += 1
    if app.gameOverCounter > 160:
        app.crahsed = False
        setActiveScreen('gameOver')
    if not withinTrack(app):
        app.crashed = True
        app.gameOver = True
        app.carSpeed = 0

def withinTrack(app):
    curTrackZones = app.selectedTrack.zones
    for x1,x2,y1,y2 in curTrackZones:
        if x1 <= app.carX <= x2 and y1 <= app.carY <= y2:
            return True
    return False

#############################
# freeRoam
#############################

def freeRoam_redrawAll(app):
    drawCurrentTrack(app)
    drawCar(app)
    if app.crashed:
        drawCrashFire(app)
    if app.paused:
        drawGamePauseScreen(app)

def freeRoam_onKeyHold(app,keys):
    if not app.paused and not app.crashed:
        controlCarStatesOnHold(app,keys)

def freeRoam_onKeyRelease(app,keys):
    controlCarStatesOnRelease(app,keys)

def freeRoam_onStep(app):
    app.homeScreenSound.pause()
    if not app.paused:
        controlCarStateOnStep(app)
    selectionCounterLogic(app)
    crashLogic(app)
    
def freeRoam_onKeyPress(app,key):
    if key == 'p':
        app.paused = True
    if app.paused:
        if key == 'up':
            app.pauseSelection = 'Resume'
        elif key == 'down':
            app.pauseSelection = 'Exit'
        elif key == 'enter':
            if app.pauseSelection == 'Resume':
                app.paused = False
            else:
                resetApp(app)
                setActiveScreen('home')

##########################
# gameOver
##########################

def gameOver_redrawAll(app):
    drawRect(0,0,app.width,app.height,fill='silver')
    drawFinalLapTimes(app)
    optionWidth, optionHeight = (150/400) * app.width, (50/400) * app.height
    drawRect(app.width//2,(3/4) * app.height,optionWidth,optionHeight,align='center',border='black',borderWidth=2,fill='gold')
    drawLabel('Return to main menu',app.width//2,(3/4) * app.height)
    drawRect(app.width//2,(3/4) * app.height,optionWidth,optionHeight,fill=None,align='center',border='yellow',opacity=getFlashingOpacity(app))

def drawFinalLapTimes(app):
    if app.lapTimes == [None,None,None,None,None]:
        drawLabel ('No valid laps recorded!',app.width/2, app.height/2, size=20,bold=True)
        return
    adjustment = (30/400) * app.height
    numLaps = 5
    for i in range(numLaps):
        x, y = app.width//2, (1/4)*app.height + adjustment * i
        curLaptime = app.lapTimes[i]
        if curLaptime != None:
            drawLabel(f'{i + 1} : {getTime(curLaptime)}',x,y,size=20,bold=True)

def gameOver_onStep(app):
    selectionCounterLogic(app)

def gameOver_onKeyPress(app,key):
    if key == 'enter':
        resetApp(app)
        setActiveScreen('home')

def main():
    runAppWithScreens(initialScreen='load',width=500,height=500)

main()
